/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication9;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Krushna
 */
public class Admission extends javax.swing.JFrame {

    /**
     * Creates new form Admission
     */
    java.util.Date dt=new java.util.Date();
    Statement st=null;
    ResultSet rst=null;
    String gender=null;
    String category=null;
    String hsc="no",ssc="no",diploma="no",other="no";
    public Admission() {
        initComponents();
         jtfdoa.setText(""+(dt.getDate())+"/"+(dt.getMonth()+1)+"/"+(dt.getYear()+1900));
         try
        {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            Connection con=DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE","system","K");
            st=con.createStatement();
            rst=st.executeQuery("select Regid from StudReg where status='REG'");
            while(rst.next())
            {
                cbregid.addItem(rst.getString("RegId"));
            }
        }catch(SQLException ex){ex.printStackTrace();}
        catch(Exception e){e.printStackTrace();}
        show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jtfdoa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtfsname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtfpname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtfdob = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jtftotfees = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jtffeespaid = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jtfbalfees = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cbregid = new javax.swing.JComboBox();
        cbssc = new javax.swing.JCheckBox();
        cbhsc = new javax.swing.JCheckBox();
        cbdiploma = new javax.swing.JCheckBox();
        cbother = new javax.swing.JCheckBox();
        rbopen = new javax.swing.JRadioButton();
        rbreserve = new javax.swing.JRadioButton();
        rbmale = new javax.swing.JRadioButton();
        rbfemale = new javax.swing.JRadioButton();
        cbcourse = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Date Of Admission");

        jtfdoa.setEditable(false);
        jtfdoa.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jtfdoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfdoaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 24)); // NOI18N
        jLabel1.setText("Admission Form");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Select Reg ID");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Student Name");

        jtfsname.setEditable(false);
        jtfsname.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jtfsname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfsnameActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Parents Name");

        jtfpname.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jtfpname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfpnameActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel13.setText("Gender");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel14.setText("Enter DOB(MM DD YYYY)");

        jtfdob.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jtfdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfdobActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel15.setText("Select Course");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel16.setText("Category ");

        jLabel17.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel17.setText("Select Previous Qualification");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel18.setText("Total Fees Applicable");

        jtftotfees.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jtftotfees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtftotfeesActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel19.setText("Fees Paid");

        jtffeespaid.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jtffeespaid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtffeespaidActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel20.setText("Balance Fees");

        jtfbalfees.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        jtfbalfees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfbalfeesActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cbregid.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        cbregid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select-" }));
        cbregid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbregidActionPerformed(evt);
            }
        });

        cbssc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbssc.setText("SSC");
        cbssc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbsscActionPerformed(evt);
            }
        });

        cbhsc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbhsc.setText("HSC");
        cbhsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbhscActionPerformed(evt);
            }
        });

        cbdiploma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbdiploma.setText("Diploma");
        cbdiploma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdiplomaActionPerformed(evt);
            }
        });

        cbother.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbother.setText("Other");
        cbother.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbotherActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbopen);
        rbopen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbopen.setText("Open");
        rbopen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbopenActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbreserve);
        rbreserve.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbreserve.setText("Reserve");
        rbreserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbreserveActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbmale);
        rbmale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbmale.setText("M");
        rbmale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbmaleActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbfemale);
        rbfemale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbfemale.setText("F");
        rbfemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbfemaleActionPerformed(evt);
            }
        });

        cbcourse.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        cbcourse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Select-", "FYBCA", "FYB.Sc.CS", "FYB.Sc.B.I.", "FY M.Sc.S.E." }));
        cbcourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcourseActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Confirm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rbopen)
                                                .addGap(40, 40, 40)
                                                .addComponent(rbreserve))
                                            .addComponent(jtfdob, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(83, 83, 83)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(rbfemale)
                                                .addGap(31, 31, 31)
                                                .addComponent(rbmale))
                                            .addComponent(jtfsname, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfpname, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbregid, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfdoa, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(11, 11, 11))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtftotfees)
                                    .addComponent(jtffeespaid)
                                    .addComponent(jtfbalfees)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbssc)
                                        .addGap(10, 10, 10)
                                        .addComponent(cbhsc)
                                        .addGap(10, 10, 10)
                                        .addComponent(cbdiploma)
                                        .addGap(10, 10, 10)
                                        .addComponent(cbother))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jButton1)
                        .addGap(91, 91, 91)
                        .addComponent(jButton2)))
                .addGap(142, 142, 142))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfdoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbregid, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfsname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfpname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbfemale)
                    .addComponent(rbmale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfdob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbcourse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbopen)
                    .addComponent(rbreserve))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbssc)
                    .addComponent(cbhsc)
                    .addComponent(cbdiploma)
                    .addComponent(cbother))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtftotfees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtffeespaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfbalfees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfdoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfdoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfdoaActionPerformed

    private void jtfsnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfsnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfsnameActionPerformed

    private void jtfpnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfpnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfpnameActionPerformed

    private void jtfdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfdobActionPerformed

    private void jtftotfeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtftotfeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtftotfeesActionPerformed

    private void jtffeespaidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtffeespaidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtffeespaidActionPerformed

    private void jtfbalfeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfbalfeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfbalfeesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
            st.executeUpdate("insert into studadm values("+cbregid.getSelectedItem()+","+jtfdoa.getText()+","+jtfsname.getText()+","+jtfpname.getText()+","+gender+","+jtfdob.getText()+","+cbcourse.getSelectedItem()+","+category+","+ssc+","+ssc+","+hsc+","+diploma+","+other+","+jtftotfees.getText()+","+jtffeespaid.getText()+","+jtfbalfees.getText()+")");
            JOptionPane.showMessageDialog(this,"Admission Confirmed");
        }catch(SQLException ex){ex.printStackTrace();}
        /*if(jtfdoa.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "AC Year is Empty");
        else if(tfregid.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "Registration ID is Empty");
        else if(tfsname.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "Student Name is Empty");
        else if(tfdor.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "Date Of Registration is Empty");
        else if(tfscontno.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "Student Contact No is Empty");
        else if(tfpcontno.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "Parent Contact No is Empty");
        else if(taddress.getText().isEmpty())
        JOptionPane.showMessageDialog(this, "Address is Empty");
        else
        {
            try
            {
                st.executeUpdate("Insert into StudReg values('"+tfregid.getText()+"','"+cbregid.getSelectedItem()+"','"+tfsname.getText()+"','"+tfdor.getText()+"','"+tfscontno.getText()+"','"+tfpcontno.getText()+"','"+taddress.getText()+"','REG','"+jtfdoa.getText()+"')");
                JOptionPane.showMessageDialog(this,"Registration Successful");
                dispose();
            }catch(SQLException ex){ex.printStackTrace();}
        }*/

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbregidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbregidActionPerformed
        // TODO add your handling code here:
        try
        {
            rst=st.executeQuery("select studname from studreg where REGID='"+cbregid.getSelectedItem()+"'");
            if(rst.next())
            {
                jtfsname.setText(rst.getString("studname"));
            }
        }catch(SQLException ex){ex.printStackTrace();}
       
    }//GEN-LAST:event_cbregidActionPerformed

    private void cbsscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbsscActionPerformed
        // TODO add your handling code here:
        if(cbssc.isSelected())
            ssc="Yes";
        else
            ssc="No";
    }//GEN-LAST:event_cbsscActionPerformed

    private void cbhscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbhscActionPerformed
        // TODO add your handling code here:
        if(cbhsc.isSelected())
            hsc="Yes";
        else
            hsc="No";
    }//GEN-LAST:event_cbhscActionPerformed

    private void cbdiplomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdiplomaActionPerformed
        // TODO add your handling code here:
        if(cbdiploma.isSelected())
            diploma="Yes";
        else
            diploma="No";
    }//GEN-LAST:event_cbdiplomaActionPerformed

    private void cbotherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbotherActionPerformed
        // TODO add your handling code here:
        if(cbother.isSelected())
            other="Yes";
        else
            other="No";
    }//GEN-LAST:event_cbotherActionPerformed

    private void cbcourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcourseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcourseActionPerformed

    private void rbmaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbmaleActionPerformed
        // TODO add your handling code here:
        gender="Male";
    }//GEN-LAST:event_rbmaleActionPerformed

    private void rbfemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbfemaleActionPerformed
        // TODO add your handling code here:
        gender="Female";
    }//GEN-LAST:event_rbfemaleActionPerformed

    private void rbopenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbopenActionPerformed
        // TODO add your handling code here:
        category="Open";
    }//GEN-LAST:event_rbopenActionPerformed

    private void rbreserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbreserveActionPerformed
        // TODO add your handling code here:
        category="Reserve";
    }//GEN-LAST:event_rbreserveActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int totfees=Integer.parseInt(jtftotfees.getText());
        int feespaid=Integer.parseInt(jtffeespaid.getText());
        int balfees=totfees-feespaid;
        jtfbalfees.setText(""+balfees);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admission().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox cbcourse;
    private javax.swing.JCheckBox cbdiploma;
    private javax.swing.JCheckBox cbhsc;
    private javax.swing.JCheckBox cbother;
    private javax.swing.JComboBox cbregid;
    private javax.swing.JCheckBox cbssc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtfbalfees;
    private javax.swing.JTextField jtfdoa;
    private javax.swing.JTextField jtfdob;
    private javax.swing.JTextField jtffeespaid;
    private javax.swing.JTextField jtfpname;
    private javax.swing.JTextField jtfsname;
    private javax.swing.JTextField jtftotfees;
    private javax.swing.JRadioButton rbfemale;
    private javax.swing.JRadioButton rbmale;
    private javax.swing.JRadioButton rbopen;
    private javax.swing.JRadioButton rbreserve;
    // End of variables declaration//GEN-END:variables
}
